root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build   main.go minio_handler.go mysql_handler.go "
  bin = "main.exe"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]